#
# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DEVICE_PATH := device/huawei/venus

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a53

TARGET_BOARD_SUFFIX := _64
TARGET_IS_64_BIT := true

TARGET_BOARD_PLATFORM_GPU := Mali-T830
TARGET_BOARD_PLATFORM := hi6250
BOARD_VENDOR_PLATFORM := hi6250

# Bluetooth
BOARD_USES_LIBBT_WRAPPER := true

# Bootanimation
TARGET_BOOTANIMATION_HALF_RES := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := hi6250
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Build rules
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Display
TARGET_SCREEN_DENSITY := 440
TARGET_ADDITIONAL_GRALLOC_10_USAGE_BITS := 0x2080000U
TARGET_DISABLE_POSTRENDER_CLEANUP := true

# Encryption
TARGET_PROVIDES_KEYMASTER := true

# HIDL
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/prebuilts/manifest.xml
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/prebuilts/compatibility_matrix.xml

# Kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_BASE := 0x00478000
BOARD_KERNEL_CMDLINE := loglevel=4 coherent_pool=512K page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M androidboot.selinux=permissive
BOARD_KERNEL_CMDLINE += loop.max_part=7
BOARD_KERNEL_CMDLINE += androidboot.super_partition=system
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x07b88000 --tags_offset 0x07588000
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_KERNEL_SOURCE := kernel/huawei/venus
TARGET_KERNEL_CONFIG := hi6250_defconfig
TARGET_KERNEL_LLVM_BINUTILS := false

# Lights
TARGET_PROVIDES_LIBLIGHT := true

# Metadata
BOARD_USES_METADATA_PARTITION := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_USERDATAIMAGE_PARTITION_SIZE := 11546918912

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4

# Partitions - dynamic
BOARD_SUPER_PARTITION_BLOCK_DEVICES := cust patch product system vendor
BOARD_SUPER_PARTITION_CUST_DEVICE_SIZE := 201326592
BOARD_SUPER_PARTITION_PATCH_DEVICE_SIZE := 33554432
BOARD_SUPER_PARTITION_PRODUCT_DEVICE_SIZE := 201326592
BOARD_SUPER_PARTITION_SYSTEM_DEVICE_SIZE := 2080374784
BOARD_SUPER_PARTITION_VENDOR_DEVICE_SIZE := 637534208
BOARD_SUPER_PARTITION_SIZE := 3154116608
BOARD_SUPER_PARTITION_GROUPS := huawei_dynamic_partitions
BOARD_HUAWEI_DYNAMIC_PARTITIONS_PARTITION_LIST := odm product system system_ext vendor
BOARD_HUAWEI_DYNAMIC_PARTITIONS_SIZE := 3149922304 #$(shell expr $(BOARD_SUPER_PARTITION_SIZE) - 4194304)
BOARD_SUPER_PARTITION_METADATA_DEVICE := system

BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 31457280 # 30MB
BOARD_VENDORIMAGE_PARTITION_RESERVED_SIZE := 31457280 # 30MB
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 849346560 #810
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE := 314572800 #300

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USES_MKE2FS := true

BOARD_ROOT_EXTRA_FOLDERS :=  \
	3rdmodem \
	3rdmodemnvm \
	3rdmodemnvmbkp \
	sec_storage \
	modem_log \
	mnvm2:0 \
	modem_fw \
	splash2
    
BOARD_ROOT_EXTRA_SYMLINKS += /odm/hw_odm:/hw_odm
	
# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/fstab.hi6250
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
BOARD_USES_FULL_RECOVERY_IMAGE := true
TARGET_RECOVERY_UPDATER_LIBS := librecovery_updater_huawei
TARGET_RECOVERY_UI_BLANK_UNBLANK_ON_INIT := true

# Releasetools
TARGET_RELEASETOOLS_EXTENSIONS := $(DEVICE_PATH)/releasetools

# RIL
ENABLE_VENDOR_RIL_SERVICE := true
BOARD_PROVIDES_LIBRIL := true

# Vendor
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM := odm

# Vendor Init
TARGET_INIT_VENDOR_LIB := //$(DEVICE_PATH):init_hisi
TARGET_RECOVERY_DEVICE_MODULES := init_hisi

# Verity - Only needed for signing
BOARD_AVB_ENABLE := false

# VNDK
PRODUCT_USE_VNDK_OVERRIDE := true
PRODUCT_FULL_TREBLE_OVERRIDE := true
PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE := true

# Sepolicy
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
SELINUX_IGNORE_NEVERALLOWS := true

# Vulkan
TARGET_USES_VULKAN := true

# Wifi
WPA_SUPPLICANT_VERSION		:= VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER	:= NL80211
BOARD_HOSTAPD_DRIVER		:= NL80211
CONFIG_DRIVER_NL80211		:= y

# Vendor Security patch level
VENDOR_SECURITY_PATCH := 2023-11-05

# inherit from the proprietary version
-include vendor/huawei/venus/BoardConfigVendor.mk
